  // OPTIONS FOR COMPOUNDING
/*
  'BREAK',
  'COMPOUNDRULE',
  'COMPOUNDMIN',
  'COMPOUNDFLAG',
  'COMPOUNDFIRST',
  'COMPOUNDBEGIN',
  'COMPOUNDMIDDLE',
  'COMPOUNDLAST',
  'COMPOUNDEND',
  'ONLYINCOMPOUND',
  'FORBIDDENWORD',

  'COMPOUNDPERMITFLAG',
  'COMPOUNDFORBIDFLAG',

  'COMPOUNDROOT',
  'COMPOUNDWORDMAX',
  'CHECKCOMPOUNDDUP',
  'CHECKCOMPOUNDREP',
  'CHECKCOMPOUNDCASE',
  'CHECKCOMPOUNDTRIPLE',
  'SIMPLIFIEDTRIPLE',
  'CHECKCOMPOUNDPATTERN',
  'COMPOUNDSYLLABLE',
  'SYLLABLENUM',

  'CIRCUMFIX',

*/